version: '3.7'

services:
    web:
        build: ./weightwhat/backend/
        command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
        volumes:
            - ./weightwhat/backend/:/usr/src/weightwhat
        ports:
            - 8002:8000
        env_file:
            - .env
    db:
        image: postgres:12.1-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=username
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=weightwhat_dev
        ports:
            - "5432:5432"
volumes:
    postgres_data:
